# Generated by Django 4.2.10 on 2025-01-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtu_app', '0002_alter_customuser_email_alter_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
