# Generated by Django 4.2.10 on 2025-01-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtu_app', '0004_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='api_return_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
